version: "3.9"

services:
  monitor-db:
    image: postgres:16
    container_name: monitor-db
    environment:
      POSTGRES_USER: monitor
      POSTGRES_PASSWORD: monitor
      POSTGRES_DB: monitor
    volumes:
      - monitor_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  monitor-backend:
    build:
      context: ./backend
    container_name: monitor-backend
    depends_on:
      - monitor-db
    environment:
      - DATABASE_URL=postgresql+psycopg2://monitor:monitor@monitor-db:5432/monitor
      - JWT_SECRET=please-change-this-in-prod
      - JWT_EXPIRE_MINUTES=1440
    ports:
      - "8000:8000"

  monitor-agent:
    build:
      context: ./agent
    container_name: monitor-agent
    depends_on:
      - monitor-backend
    environment:
      - API_URL=http://monitor-backend:8000/api/v1
    # so agent logs stream to your console
    stdin_open: true
    tty: true

volumes:
  monitor_data:
