substitutions:
  _IMAGE_NAME: "backend" 

steps:
  # 1️⃣ Build the Docker container image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/server-metrics-repo/${_IMAGE_NAME}:$BUILD_ID'
      - '.'

  # 2️⃣ Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/server-metrics-repo/${_IMAGE_NAME}:$BUILD_ID'

  # 3️⃣ Run Alembic migrations (requires database credentials)
  - name: "gcr.io/google-appengine/exec-wrapper"
    id: 'Migrate DB'
    entrypoint: 'bash'
    args:
      - "-c"
      - |
        # Note: The database.py file requires DB_USER, DB_PASS, and DB_NAME secrets to be set
        /buildstep/execute.sh \
        -i us-central1-docker.pkg.dev/$PROJECT_ID/server-metrics-repo/${_IMAGE_NAME}:$BUILD_ID \
        -s $$CONNECTION_NAME \
        -e DATABASE_URL=$$DATABASE_URL \
        -e DB_USER=$$DB_USER \
        -e DB_PASS=$$DB_PASS \
        -e DB_NAME=$$DB_NAME \
        -e DB_CONNECTION_NAME=$$DB_CONNECTION_NAME \
        -- alembic upgrade head
    secretEnv: ['DATABASE_URL', 'CONNECTION_NAME', 'DB_USER', 'DB_PASS', 'DB_NAME', 'DB_CONNECTION_NAME']

# 4️⃣ Deploy the container to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy'
    entrypoint: 'bash'
    args:
      - "-c"
      - |
        gcloud run deploy ${_IMAGE_NAME} \
          --image=us-central1-docker.pkg.dev/$PROJECT_ID/server-metrics-repo/${_IMAGE_NAME}:$BUILD_ID \
          --region=us-central1 \
          --platform=managed \
          --allow-unauthenticated \
          --add-cloudsql-instances="$$CONNECTION_NAME" \
          --set-env-vars="CONNECTION_NAME=$$CONNECTION_NAME,DATABASE_URL=$$DATABASE_URL,DB_CONNECTION_NAME=$$DB_CONNECTION_NAME,DB_NAME=$$DB_NAME,DB_PASS=$$DB_PASS,DB_USER=$$DB_USER,FRONTEND_URL=$$FRONTEND_URL,GITHUB_CLIENT_ID=$$GITHUB_CLIENT_ID,GITHUB_CLIENT_SECRET=$$GITHUB_CLIENT_SECRET,GOOGLE_API_KEY=$$GOOGLE_API_KEY,GOOGLE_CLIENT_ID=$$GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET=$$GOOGLE_CLIENT_SECRET,JWT_ALGORITHM=$$JWT_ALGORITHM,JWT_EXPIRE_MINUTES=$$JWT_EXPIRE_MINUTES,JWT_SECRET=$$JWT_SECRET,SENDGRID_API_KEY=$$SENDGRID_API_KEY,SESSION_SECRET_KEY=$$SESSION_SECRET_KEY,SMTP_SENDER_EMAIL=$$SMTP_SENDER_EMAIL,VITE_API_BASE_URL=$$VITE_API_BASE_URL"
    secretEnv: 
      - 'CONNECTION_NAME'
      - 'DATABASE_URL'
      - 'DB_CONNECTION_NAME'
      - 'DB_NAME'
      - 'DB_PASS'
      - 'DB_USER'
      - 'FRONTEND_URL'
      - 'GITHUB_CLIENT_ID'
      - 'GITHUB_CLIENT_SECRET'
      - 'GOOGLE_API_KEY'
      - 'GOOGLE_CLIENT_ID'
      - 'GOOGLE_CLIENT_SECRET'
      - 'JWT_ALGORITHM'
      - 'JWT_EXPIRE_MINUTES'
      - 'JWT_SECRET'
      - 'SENDGRID_API_KEY'
      - 'SESSION_SECRET_KEY'
      - 'SMTP_SENDER_EMAIL'
      - 'VITE_API_BASE_URL'
      
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/server-metrics-repo/${_IMAGE_NAME}:$BUILD_ID'

# -----------------------------
# Secret Manager configuration (Expanded to 19 Secrets)
# -----------------------------
availableSecrets:
  secretManager:
    # --- All 19 Secrets Mapped from Secret Manager ---
    - versionName: projects/$PROJECT_ID/secrets/CONNECTION_NAME/versions/latest
      env: 'CONNECTION_NAME'
    - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
      env: 'DATABASE_URL'
    - versionName: projects/$PROJECT_ID/secrets/DB_CONNECTION_NAME/versions/latest
      env: 'DB_CONNECTION_NAME'
    - versionName: projects/$PROJECT_ID/secrets/DB_NAME/versions/latest
      env: 'DB_NAME'
    - versionName: projects/$PROJECT_ID/secrets/DB_PASS/versions/latest
      env: 'DB_PASS'
    - versionName: projects/$PROJECT_ID/secrets/DB_USER/versions/latest
      env: 'DB_USER'
    - versionName: projects/$PROJECT_ID/secrets/FRONTEND_URL/versions/latest
      env: 'FRONTEND_URL'
    - versionName: projects/$PROJECT_ID/secrets/GITHUB_CLIENT_ID/versions/latest
      env: 'GITHUB_CLIENT_ID'
    - versionName: projects/$PROJECT_ID/secrets/GITHUB_CLIENT_SECRET/versions/latest
      env: 'GITHUB_CLIENT_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_API_KEY/versions/latest
      env: 'GOOGLE_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_CLIENT_ID/versions/latest
      env: 'GOOGLE_CLIENT_ID'
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_CLIENT_SECRET/versions/latest
      env: 'GOOGLE_CLIENT_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/JWT_ALGORITHM/versions/latest
      env: 'JWT_ALGORITHM'
    - versionName: projects/$PROJECT_ID/secrets/JWT_EXPIRE_MINUTES/versions/latest
      env: 'JWT_EXPIRE_MINUTES'
    - versionName: projects/$PROJECT_ID/secrets/JWT_SECRET/versions/latest
      env: 'JWT_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/SENDGRID_API_KEY/versions/latest
      env: 'SENDGRID_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/SESSION_SECRET_KEY/versions/latest
      env: 'SESSION_SECRET_KEY'
    - versionName: projects/$PROJECT_ID/secrets/SMTP_SENDER_EMAIL/versions/latest
      env: 'SMTP_SENDER_EMAIL'
    - versionName: projects/$PROJECT_ID/secrets/VITE_API_BASE_URL/versions/latest
      env: 'VITE_API_BASE_URL'
    # ----------------------------------------------------

options:
  logging: CLOUD_LOGGING_ONLY