substitutions:
  _IMAGE_NAME: "backend" 

steps:
  # 1️⃣ Build the Docker container image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/server-metrics-repo/${_IMAGE_NAME}:$BUILD_ID'
      - '.'

  # 2️⃣ Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/server-metrics-repo/${_IMAGE_NAME}:$BUILD_ID'

  # 3️⃣ Run Alembic migrations using DATABASE_URL secret
  - name: "gcr.io/google-appengine/exec-wrapper"
    id: 'Migrate DB'
    entrypoint: 'bash'
    args:
      - "-c"
      - |
        /buildstep/execute.sh \
        -i us-central1-docker.pkg.dev/$PROJECT_ID/server-metrics-repo/${_IMAGE_NAME}:$BUILD_ID \
        -s $$CONNECTION_NAME -e DATABASE_URL=$$DATABASE_URL \
        -- alembic upgrade head
    secretEnv: ['DATABASE_URL', 'CONNECTION_NAME']

  # 4️⃣ Deploy the container to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_IMAGE_NAME}'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/server-metrics-repo/${_IMAGE_NAME}:$BUILD_ID'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=DATABASE_URL=$$DATABASE_URL'
    secretEnv: ['DATABASE_URL']

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/server-metrics-repo/${_IMAGE_NAME}:$BUILD_ID'

# -----------------------------
# Secret Manager configuration
# -----------------------------
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
      env: 'DATABASE_URL'
    - versionName: projects/$PROJECT_ID/secrets/CONNECTION_NAME/versions/latest
      env: 'CONNECTION_NAME'

options:
  logging: CLOUD_LOGGING_ONLY
