"""Add type column alert_rules

Revision ID: 1834a7d271a8
Revises: 19e7aa25f892
Create Date: 2025-11-26 12:37:31.021085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1834a7d271a8'
down_revision: Union[str, Sequence[str], None] = '19e7aa25f892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE TYPE alertruletype AS ENUM ('THRESHOLD', 'ANOMALY')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_rules', sa.Column('type', sa.Enum('THRESHOLD', 'ANOMALY', name='alertruletype'), nullable=True))
    op.execute("UPDATE alert_rules SET type='THRESHOLD' WHERE type IS NULL")
    op.alter_column('alert_rules', 'type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('alert_rules', 'type')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_rules', 'type')
    # ### end Alembic commands ###
