"""Add metric_baselines table

Revision ID: 19e7aa25f892
Revises: 426678c46c3d
Create Date: 2025-11-23 13:22:43.284128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e7aa25f892'
down_revision: Union[str, Sequence[str], None] = '426678c46c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('hour_of_day', sa.Integer(), nullable=False),
    sa.Column('mean_value', sa.Float(), nullable=False),
    sa.Column('std_dev_value', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'metric_name', 'hour_of_day', name='_server_metric_hour_uc')
    )
    op.create_index(op.f('ix_metric_baselines_id'), 'metric_baselines', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_baselines_id'), table_name='metric_baselines')
    op.drop_table('metric_baselines')
    # ### end Alembic commands ###
