"""Add webhook_url to servers table

Revision ID: 2c09a02c7e43
Revises: 7911e0d38331
Create Date: 2025-11-09 14:17:17.804841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c09a02c7e43'
down_revision: Union[str, Sequence[str], None] = '7911e0d38331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_alert_rules_name'), 'alert_rules', ['name'], unique=False)
    op.add_column('servers', sa.Column('webhook_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'webhook_url')
    op.drop_index(op.f('ix_alert_rules_name'), table_name='alert_rules')
    # ### end Alembic commands ###
