"""Add relationship between servers and logs

Revision ID: 3d1d39c42c90
Revises: 8d2a2a81e893
Create Date: 2025-11-09 23:40:10.333900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d1d39c42c90'
down_revision: Union[str, Sequence[str], None] = '8d2a2a81e893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
