"""Add process metrics to Metric table

Revision ID: 744c9a12f001
Revises: fe7b2557ebe0
Create Date: 2025-11-08 01:15:04.817510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '744c9a12f001'
down_revision: Union[str, Sequence[str], None] = 'fe7b2557ebe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('processes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metrics', 'processes')
    # ### end Alembic commands ###
