"""Add webhook_headers to servers table

Revision ID: 8d2a2a81e893
Revises: ce6a61c07a4f
Create Date: 2025-11-09 20:34:52.208066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d2a2a81e893'
down_revision: Union[str, Sequence[str], None] = 'ce6a61c07a4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('webhook_headers', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'webhook_headers')
    # ### end Alembic commands ###
