"""Add webhook_format to servers table

Revision ID: ce6a61c07a4f
Revises: 2c09a02c7e43
Create Date: 2025-11-09 14:32:15.445350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce6a61c07a4f'
down_revision: Union[str, Sequence[str], None] = '2c09a02c7e43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('webhook_format', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'webhook_format')
    # ### end Alembic commands ###
