"""Add foreign key relationship between servers and logs

Revision ID: e4fffcd9fc3d
Revises: 3d1d39c42c90
Create Date: 2025-11-09 23:46:43.945302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4fffcd9fc3d'
down_revision: Union[str, Sequence[str], None] = '3d1d39c42c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'logs', 'servers', ['server_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'logs', type_='foreignkey')
    # ### end Alembic commands ###
